### ISSUE TITLE
[Pixel Grid] Polygon Cells

### ISSUE THREAD

**Issue by DeflatedPickle** [DeflatedPickle/Rawky#29]
Polygon shapes should be supported for grid cells insead of using rectangles. Whilst this would break exporting some shapes to images, an extra text input for how accurate the output should be could be added. With the RAWR format, no additional text box would be needed.

With hexagon cells, an accuracy of 1 would result in squares, but an accuracy of 3 would result in shapes looking like the ship in Space Invaders. An accuracy of 7 would result in a low-resolution hexagon.

With these shapes, layout methods for the could be made. Such as rotating the polygon each odd cell, or resizing them.

### To-Do
- [x] Polygon grid cells (added in 5c08da3)
- [ ] Polygon builder dialog
- [ ] Layout methods
- [ ] Layout dialog (is this possible?)
